name: is-next-compat

# ! If you want to use this workflow, the following secrets must be defined:
# ! - MONGODB_URI
# ! - GH_TOKEN

on:
  workflow_dispatch: # * Treated like a scheduled run
  schedule:
    - cron: '0 12 */1 * *'

env:
  # * Selectively enable debugger verbose output in the pipeline
  # ? See also: https://www.npmjs.com/package/debug#wildcards
  # DEBUG: 'next-test-api-route-handler:*'
  NODE_CURRENT_VERSION: 18.x
  NODE_OLDER_VERSIONS: '"12.x", "14.x", "16.x"'

jobs:
  metadata:
    name: 'gather-metadata'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      node-matrix: ${{ steps.set-matrix.outputs.node-matrix }}
    steps:
      - name: Report DEBUG mode status
        run: |
          if ! [ -z "$DEBUG" ]; then
            echo 'PIPELINE IS RUNNING IN DEBUG MODE!'
          else
            echo '(pipeline is not running in debug mode)'
          fi

      - name: Gather metadata
        id: set-matrix
        run: |
          echo "::set-output name=node-matrix::{\"node\":[$NODE_OLDER_VERSIONS, \"$NODE_CURRENT_VERSION\"]}"
          ! [ -z "$DEBUG" ] && echo "set-output name=node-matrix::{\"node\":[$NODE_OLDER_VERSIONS, \"$NODE_CURRENT_VERSION\"]}" || true

  check-compat:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: metadata
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.metadata.outputs.node-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache npm
        uses: actions/cache@v2.1.6
        id: cache-npm
        with:
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-keys: npm-${{ runner.os }}-

      - name: Install CI dependencies
        run: npm ci

      - name: Build distributables
        run: npm run build-dist

      - name: Build externals
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run build-externals

      - name: Run is-next-compat
        run:
          node external-scripts/bin/is-next-compat.js ${{
          env.NODE_CURRENT_VERSION }}
