name: run-apollo-example

on:
  workflow_dispatch: # * Treated like a scheduled run
  schedule:
    - cron: '0 12 */1 * *'

env:
  # * Selectively enable debugger verbose output in the pipeline
  # ? See also: https://www.npmjs.com/package/debug#wildcards
  # DEBUG: 'next-test-api-route-handler:*'
  NODE_CURRENT_VERSION: 15.x

jobs:
  check-compat:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Report DEBUG mode status
        run: |
          if ! [ -z "$DEBUG" ]; then
            echo 'PIPELINE IS RUNNING IN DEBUG MODE!'
          else
            echo '(pipeline is not running in debug mode)'
          fi

      - name: Run apollo terminal example
        # https://bit.ly/38702j0
        run: |
          git clone --depth=1 https://github.com/vercel/next.js /tmp/ntarh-test
          cd /tmp/ntarh-test/examples/api-routes-apollo-server-and-client
          npm install
          npm install next-test-api-route-handler jest babel-jest @babel/core @babel/preset-env graphql-tools
          # You could test with an older version of Next.js if you want, e.g.:
          # npm install next@9.0.6 --force
          # Or even older:
          # npm install next@9.0.0 next-server --force
          echo 'module.exports={"presets":["next/babel"]};' > babel.config.js
          mkdir test
          curl -o test/my.test.js https://raw.githubusercontent.com/Xunnamius/next-test-api-route-handler/main/apollo_test_raw
          npx jest
